<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My App</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->    
  </head>
  <body>

    <div class="container">
      <!-- header area -->
      <div class="panel panel-default">
        <div class="panel-heading clearfix">
          <h4 class="pull-left">Users</h4>
          <div class="btn-group pull-right">
            <a role="button" class="btn btn-primary" href="<?php echo $data['router']->pathFor('admin-users-save'); ?>">Add user</a>
          </div>
        </div>
      </div>  
      <!-- header area ends -->
      
      <!-- content area -->
      <?php if (count($data['active-users']) > 0): ?>
      <div class="panel panel-default">
        <div class="panel-heading clearfix">
          <h4 class="pull-left">Active Users</h4>
        </div>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Email address</th>
              <th></th>
            </tr>
          </thead>
        <?php foreach ($data['active-users'] as $user): ?>
          <tr>
            <td><?php echo $user->firstName; ?> <?php echo $user->lastName; ?></td>
            <td><?php echo $user->email; ?></td>
            <td><a href="<?php echo $data['router']->pathFor('admin-users-deactivate', array('id' => $user->id)); ?>" class="btn btn-danger">Deactivate</a></td> 
          </tr>
        <?php endforeach; ?>
        </table>
      </div>
      <?php else: ?>
      <div>
        <div class="alert alert-info">
          No users found. <a role="button" class="btn btn-primary" href="<?php echo $data['router']->pathFor('admin-users-save'); ?>">Why not create one?</a>
        </div>
      </div>  
      <?php endif; ?>

      <?php if (count($data['inactive-users']) > 0): ?>
      <div class="panel panel-default">
        <div class="panel-heading clearfix">
          <h4 class="pull-left">Inactive Users</h4>
        </div>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Email address</th>
              <th></th>
            </tr>
          </thead>
        <?php foreach ($data['inactive-users'] as $user): ?>
          <tr>
            <td><?php echo $user->firstName; ?> <?php echo $user->lastName; ?></td>
            <td><?php echo $user->email; ?></td>
            <td><a href="<?php echo $data['router']->pathFor('admin-users-activate', array('id' => $user->id)); ?>" class="btn btn-success">Activate</a></td> 
          </tr>
        <?php endforeach; ?>
        </table>
      </div>
      <?php endif; ?>
      <!-- content area ends-->
      
      <!-- footer -->
      <div class="container">
      <p class="text-center">
        <a href="<?php echo $data['router']->pathFor('legal'); ?>" role="button" class="btn btn-default btn">Legal</a>
      </p>
      </div> 
      <!-- footer ends -->
    </div> 

     
  </body>
</html>