<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My App</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->    
  </head>
  <body>

    <div class="container">
      <!-- header area -->
      <div class="panel panel-default">
        <div class="panel-heading clearfix">
          <h4 class="pull-left">Users</h4>
          <div class="btn-group pull-right">
            <a role="button" class="btn btn-primary" href="<?php echo $data['router']->pathFor('admin-users-index'); ?>">List users</a>
          </div>
        </div>
      </div>  
      <!-- header area ends -->
      
      <!-- content area -->
      <div>
      <?php if (!isset($_POST['submit'])): ?>
        <form method="post" action="<?php echo $data['router']->pathFor('admin-users-save'); ?>">
          <input name="id" type="hidden" value="<?php echo (isset($data['user']->id)) ? $data['user']->id : ''; ?>" />
          <div class="form-group">
            <label for="fname">First name</label>
            <input type="text" class="form-control" id="fname" name="fname" value="<?php echo (isset($data['user']->firstName)) ? $data['user']->firstName : ''; ?>">
          </div>
          <div class="form-group">
            <label for="lname">Last name</label>
            <input type="text" class="form-control" id="lname" name="lname" value="<?php echo (isset($data['user']->lastName)) ? $data['user']->lastName : ''; ?>">
          </div>
          <div class="form-group">
            <label for="email">Email address</label>
            <input type="text" class="form-control" id="email" name="email" value="<?php echo (isset($data['user']->email)) ? $data['user']->email : ''; ?>">
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password">
          </div>
          <div class="form-group">
            <label for="city">City</label>
            <input type="text" class="form-control" id="city" name="city" value="<?php echo (isset($data['user']->data->attributes->city)) ? $data['user']->data->attributes->city : ''; ?>">
          </div>
          <div class="form-group">
            <label for="occupation">Occupation</label>
            <input type="text" class="form-control" id="occupation" name="occupation" value="<?php echo (isset($data['user']->data->attributes->occupation)) ? $data['user']->data->attributes->occupation : ''; ?>">
          </div>
          <div class="form-group">
            <label for="mobilePhone">Mobile phone (with country code)</label>
            <input type="text" class="form-control" id="mobilePhone" name="mobilePhone" value="<?php echo (isset($data['user']->mobilePhone)) ? $data['user']->mobilePhone : ''; ?>">
          </div>
          <div class="form-group">
            <label for="tier">Membership tier</label>
            <select class="form-control" id="tier" name="tier">
              <option value="1" <?php echo !empty($data['user']) && !empty($data['user']->registrations[0]->roles) && ($data['user']->registrations[0]->roles[0] == 'member-gold') ? 'selected="selected"' : ''; ?>>Gold</option>
              <option value="2" <?php echo !empty($data['user']) && !empty($data['user']->registrations[0]->roles) && ($data['user']->registrations[0]->roles[0] == 'member-silver') ? 'selected="selected"' : ''; ?>>Silver</option>
            </select>
          </div>          
          <div class="form-group">
            <button type="submit" name="submit" class="btn btn-default">Save</button>
          </div>
        </form>  
      <?php else: ?>
        <div class="alert alert-success">
          <strong>Success!</strong> The user with identifier <strong><?php echo $data['user']->id; ?></strong> was successfully created or updated. <a role="button" class="btn btn-primary" href="<?php echo $data['router']->pathFor('admin-users-save'); ?>">Add another?</a>
        </div>
      <?php endif; ?> 
      </div>        
      <!-- content area ends-->
      
      <!-- footer -->
      <div class="container">
        <p class="text-center">
          <a href="<?php echo $data['router']->pathFor('legal'); ?>" role="button" class="btn btn-default btn">Legal</a>
        </p>
      </div> 
      <!-- footer ends -->
    </div> 

     
  </body>
</html>